spring:  
    profiles:  
        active:  
        - dev
---
server: 
    port: 8203
spring: 
    profiles: dev #开发环境
    application: 
        name: microservicecloud-config-client
    rabbitmq:					#本地环境不需要配置mq，但是需要启动mq,Springboot会自动连接本地mq
        host: localhost
        port: 5672
        username: guest
        password: guest    
---
server: 
    port: 8205
spring: 
    profiles: test 
    application: 
        name: microservicecloud-config-client123456
    rabbitmq:					#本地环境不需要配置mq，但是需要启动mq,Springboot会自动连接本地mq
        host: localhost
        port: 5672
        username: guest
        password: guest    
